name: magic
description: The Smartest Home Gym Ever

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  state_notifier: ^0.7.2+1
  freezed_annotation:
  flutter_state_notifier:
  scrollable_positioned_list: ^0.3.5
  riverpod_annotation: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.1.0
  list_ext: ^1.0.6
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:

  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^2.2.1
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  mockito:
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
     - assets/images/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Light.ttf
